CREATE SEQUENCE S_SUBJECT_ID START WITH 1 INCREMENT BY 50;
CREATE TABLE T_SUBJECTS
(
    SUBJECT_ID            NUMERIC(10, 0),
    SUBJECT_AUDIT_CD DATE NOT NULL DEFAULT NOW(),
    SUBJECT_AUDIT_MD DATE,
    SUBJECT_AUDIT_RD DATE,
    SUBJECT_NAME          VARCHAR(100),
    SUBJECT_STUDENT_COUNT NUMERIC(10, 0),
    SUBJECT_STUD_GROUP_ID NUMERIC(10, 0),
    SUBJECT_TEACHER_ID    NUMERIC(10, 0)
)