CREATE SEQUENCE S_TEACHER_ID START WITH 1 INCREMENT BY 50;
CREATE TABLE T_TEACHERS
(
    TEACHER_ID       NUMERIC(10, 0) NOT NULL,
    TEACHER_AUDIT_CD DATE NOT NULL DEFAULT NOW(),
    TEACHER_AUDIT_MD DATE,
    TEACHER_AUDIT_RD DATE,
    TEACHER_NAME     VARCHAR(100)   NOT NULL,
    TEACHER_SURNAME  VARCHAR(100)   NOT NULL,
    TEACHER_EMAIL    VARCHAR(100)   UNIQUE NOT NULL,
    TEACHER_PASSWORD VARCHAR(1000)  NOT NULL,
    TEACHER_IS_ADMIN BOOLEAN DEFAULT FALSE
);