CREATE SEQUENCE S_TIMESLOT_ID START WITH 1 INCREMENT BY 50;
CREATE TABLE T_TIMESLOTS(
    TIMESLOT_ID NUMERIC(10,0),
    TIMESLOT_AUDIT_CD DATE NOT NULL DEFAULT NOW(),
    TIMESLOT_AUDIT_MD DATE,
    TIMESLOT_AUDIT_RD DATE,
    TIMESLOT_DAY NUMERIC(1,0),
    TIMESLOT_SLOT NUMERIC(1,0),
    TIMESLOT_ACTIVE BOOLEAN DEFAULT FALSE
);